version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "${DB_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped 

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped 
    volumes:
      - redis_data:/data  

volumes:
  qdrant_data:
  redis_data:  